### ISSUE TITLE
ATLAS MVP: Big Data Migration Trade Study

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#126]
### 💡 Description

Investigation the fastest and most cost effective solution for migrating ATLAS data to AWS.

Data Upload Manager vs. AWS Snowball vs. Aspera (vs. Globus?)

### Sub-tasks

- [x] investigate snowball cost
- [x] investigate Aspera cost
- [x] investigate AWS DataSync

**Comment by viviant100** [comment]
Refer to the wiki "AWS Snowball Research Report on ATLAS Data Transfer" for detailed information. 

In summary, the cost to transfer 1PB of ATLAS data to the cloud using AWS Snowball is approximately $16,000 (5 Snowballs at $3,200 per 200TB-snowball, order 1 snowball at a time.). We will proceed with the DUM approach for the ATLAS data migration.

**Comment by jordanpadams** [comment]
@viviant100 can we expand this trade to include:
* Aspera
* AWS DataSync

**Comment by viviant100** [comment]
@jordanpadams done. see "IBM Aspera Research Report on ATLAS Data Transfer" for Aspera.

**Comment by jordanpadams** [comment]
thanks @viviant100 

@tloubrieu-jpl @collinss-jpl @ramesh-maddegoda FYI

**Comment by jordanpadams** [comment]
Moved to Markdown here: https://github.com/NASA-PDS/planetary-data-cloud/tree/main/docs/data-upload-study and included resolution.

@viviant100 feel free to add some additional information in the README, especially a few bullet points on your discussions with other projects. feel free to reorganize however you see fit.

**Comment by jordanpadams** [comment]
Once that is completed, feel free to close this ticket.

**Comment by viviant100** [comment]
> [@viviant100](https://github.com/viviant100) feel free to add some additional information in the README, especially a few bullet points on your discussions with other projects. feel free to reorganize however you see fit.

Those info has already been captured in the trade study. will close the ticket.
