### ISSUE TITLE
ATLAS MVP: Support Development of Initial Migration Plan and Architecture for ATLAS Survey Data

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/planetary-data-cloud#73]
## 💡 Description

- [ ] - Current status of ATLAS
    - [x] Set up kickoff meeting with SBN
- [x] - Define ATLAS MVP
    - [x] work with SBN UMD for requirement
- [x] - Plan for ATLAS
- [x] - Data to NSSDCA

**Comment by jordanpadams** [comment]
Going to have to defer this until start of B15.0 (April timeframe)

**Comment by jordanpadams** [comment]
📆 07/2024 status: Kicking off discussing at next CSS meeting on 8/16. These are initial planning activities that will not impact other implementation efforts.

**Comment by jordanpadams** [comment]
📆 08/2024 status: discussion started with SBN. initial roadmap defined
